name: Deploy to AWS

on:
  push:
    branches:
      - main # Se ejecuta cuando haces push a la rama main

env:
  AWS_REGION: eu-west-1
  ECR_CATALOG_REPO: catalog-api
  ECR_ORDERS_REPO: orders-api
  ECS_CLUSTER: ecommerce-cluster
  CATALOG_SERVICE: catalog-api-service
  ORDERS_SERVICE: orders-api-service

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    # 1. Bajar el código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Loguearse en AWS (Usando tus secretos)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # 3. Instalar Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # 4. Terraform Init & Apply (Crea la infraestructura)
    - name: Terraform Apply
      working-directory: ./infrastructure
      run: |
        terraform init
        terraform apply -auto-approve

    # 5. Login en Amazon ECR (Para poder subir imágenes)
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # 6. Build & Push CATALOG API (Go)
    - name: Build & Push Catalog API
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest # En un entorno real usaríamos el git-sha
      run: |
        cd services/catalog-api
        docker build -t $ECR_REGISTRY/$ECR_CATALOG_REPO:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_CATALOG_REPO:$IMAGE_TAG

    # 7. Build & Push ORDERS API (.NET)
    - name: Build & Push Orders API
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        cd services/orders-api
        docker build -t $ECR_REGISTRY/$ECR_ORDERS_REPO:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_ORDERS_REPO:$IMAGE_TAG

    # 8. Forzar despliegue en ECS (Para que coja las nuevas imágenes)
    - name: Force ECS Deployment
      run: |
        aws ecs update-service --cluster $ECS_CLUSTER --service $CATALOG_SERVICE --force-new-deployment
        aws ecs update-service --cluster $ECS_CLUSTER --service $ORDERS_SERVICE --force-new-deployment